### PR TITLE
Fixed wrong case in file name

### LINKED ISSUE #59: API does not work on Ubuntu servers
On Ubuntu servers, I try to start the Explorer API code and get this result:

```
jrush@unchainedindex:~/D/t/api|master✓➤ yarn start
yarn run v1.22.4
$ nodemon server.js
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module './webSockets'
Require stack:
- /home/jrush/Development/trueblocks-explorer/api/websockets/index.js
- /home/jrush/Development/trueblocks-explorer/api/chifra_stream_events.js
- /home/jrush/Development/trueblocks-explorer/api/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/jrush/Development/trueblocks-explorer/api/websockets/index.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jrush/Development/trueblocks-explorer/api/websockets/index.js',
    '/home/jrush/Development/trueblocks-explorer/api/chifra_stream_events.js',
    '/home/jrush/Development/trueblocks-explorer/api/server.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
^C⏎
```

I'm not sure, but it may be the case that the code is case sensitive on Ubuntu? I tried changing `webSockets` to `websockets` (lower case) and it changed the error message (still didn't work).

### PR DESCRIPTION
**Pull request by dszlachta**
Closes #59

### CODE REVIEW

**Comment by tjayrush** [comment]
That does not appear to work:

```
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'ws'
Require stack:
- /home/jrush/Development/trueblocks-explorer/api/websockets/websockets.js
- /home/jrush/Development/trueblocks-explorer/api/websockets/index.js
- /home/jrush/Development/trueblocks-explorer/api/chifra_stream_events.js
- /home/jrush/Development/trueblocks-explorer/api/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/jrush/Development/trueblocks-explorer/api/websockets/websockets.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jrush/Development/trueblocks-explorer/api/websockets/websockets.js',
    '/home/jrush/Development/trueblocks-explorer/api/websockets/index.js',
    '/home/jrush/Development/trueblocks-explorer/api/chifra_stream_events.js',
    '/home/jrush/Development/trueblocks-explorer/api/server.js'
  ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by tjayrush** [comment]
Thanks. This works on the machine I pointed you to, but it does not work on my local Ubuntu 18.04 box. (Unfortunately, I need the local box since it's running Ethereum.) I'll send a separate email with login info for that box. Would you mind trying to figure out what's going on there? I get this error when I try to do `yarn start` from the `./api` folder.

```
jrush@linux:~/Development/trueblocks-explorer/api$ yarn install
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.15s.
jrush@linux:~/Development/trueblocks-explorer/api$ yarn start
yarn run v1.22.4
$ nodemon server.js
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
module.js:549
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jrush/Development/trueblocks-explorer/api/websockets/websockets.js:6:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
[nodemon] app crashed - waiting for file changes before starting...
```
